### PR TITLE
Add a lot of languages

### PR DESCRIPTION
**Pull request by Aurnytoraink**
Added spanish, french, italian, dutch, polish, portuguese and russian

### CODE REVIEW

**Comment by fredldotme** [comment]
Whoah, nice number of languages in one commit. :)
LGTM +1

**Comment by fredldotme** [comment]
Could you please resolve the conflict and push again? I'll merge afterwards.

**Comment by Aurnytoraink** [comment]
Done

**Comment by fredldotme** [comment]
I actually prefer your translation over the existing ones as you are using &apos;. If you want you can replace the current one with yours completely.

**Review by Aurnytoraink — COMMENTED** [review]
Well this version sounds better in french

**Comment by Aurnytoraink** [comment]
> Well this version sounds better in french

The second commit

**Comment by fredldotme** [comment]
Alright. Thanks for the PR, well done!

**Pull request merged**
